import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const drukWide = localFont({
  src: "../font/DrukWideBold.ttf",
  variable: "--font-druk-wide",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${drukWide.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
